### ISSUE TITLE
サインアップを実行するとアプリが停止する

### ISSUE THREAD

**Issue by hideakihal** [agilecommunity/oot#82]
「アカウントをお持ちでない方は サインアップしてください。」からサインアップに移動し、メールアドレスを入力してサインアップをクリックすると、以下のエラーが出力され、アプリが停止しました。
エラーを見るとトークンの生成までは成功しているようです。

	[debug] a.s.UserService - doFindByEmailAndProvider email:hoge@gmail.com providerId:userpass
	[warn] a.s.UserService - doFindByEmailAndProvider LocalUser not found or too many email:hoge@gmail.com providerId:userpass list.size:0
	[debug] a.s.UserService - doSaveToken uuid:de8700b8-e756-46c8-83a3-ea9cccd31c93 email:hoge@gmail.com
	[debug] a.s.UserService - doSaveToken uuid:de8700b8-e756-46c8-83a3-ea9cccd31c93
	Uncaught error from thread [play-akka.actor.default-dispatcher-5] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[play]
	java.lang.ExceptionInInitializerError
	        at controllers.Registration.startSignUp(Registration.java:95)
	        at Routes$$anonfun$routes$1$$anonfun$applyOrElse$26$$anonfun$apply$26.apply(routes_routing.scala:377)
	[ERROR] [01/12/2015 15:46:18.608] [play-akka.actor.default-dispatcher-5] [ActorSystem(play)] Uncaught error from thread [play-ak        at Routes$$anonfun$routes$1$$anonfun$applyOrElse$26$$anonfun$app
	ly$26.apply(routes_routing.scala:377)
	ka.actor.default-dispatcher-5] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled
	java.lang.ExceptionInInitializerError
	        at play.core.Router$HandlerInvoker$$anon$7$$anon$2.invocation(Router.scala:183)
	        at controllers.Registration.startSignUp(Registration.java:95)
	        at play.core.Router$Routes$$anon$1.invocation(Router.scala:377)
	        at Routes$$anonfun$routes$1$$anonfun$applyOrElse$26$$anonfun$apply$26.apply(routes_routing.scala:377)
	        at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:56)
	        at Routes$$anonfun$routes$1$$anonfun$applyOrElse$26$$anonfun$apply$26.apply(routes_routing.scala:377)
	        at play.GlobalSettings$1.call(GlobalSettings.java:64)
	        at play.core.Router$HandlerInvoker$$anon$7$$anon$2.invocation(Router.scala:183)
	        at filters.RequireCSRFCheck4NgAction.call(RequireCSRFCheck4NgAction.java:49)
	        at play.core.Router$Routes$$anon$1.invocation(Router.scala:377)
	        at play.core.j.JavaAction$$anon$3.apply(JavaAction.scala:91)
	        at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:56)
	        at play.core.j.JavaAction$$anon$3.apply(JavaAction.scala:90)
	        at play.GlobalSettings$1.call(GlobalSettings.java:64)
	        at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:82)
	        at filters.RequireCSRFCheck4NgAction.call(RequireCSRFCheck4NgAction.java:49)
	        at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:82)
	        at play.core.j.JavaAction$$anon$3.apply(JavaAction.scala:91)
	        at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
	        at play.core.j.JavaAction$$anon$3.apply(JavaAction.scala:90)
	        at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:249)
	        at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:82)
	        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	        at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:82)
	        at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:37)
	        at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
	        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:42)
	        at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:249)
	        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:386)
	        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	        at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:37)
	        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:42)
	        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:386)
	        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
	        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	Caused by: java.util.NoSuchElementException: None.get
	        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	        at scala.None$.get(Option.scala:313)
	        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	        at scala.None$.get(Option.scala:311)
	        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
	        at securesocial.core.providers.utils.Mailer$.<init>(Mailer.scala:33)
	Caused by: java.util.NoSuchElementException: None.get
	        at securesocial.core.providers.utils.Mailer$.<clinit>(Mailer.scala)
	        at scala.None$.get(Option.scala:313)
	        ... 22 more
	        at scala.None$.get(Option.scala:311)
	        at securesocial.core.providers.utils.Mailer$.<init>(Mailer.scala:33)
	        at securesocial.core.providers.utils.Mailer$.<clinit>(Mailer.scala)
	        ... 22 more
	
	[error] a.a.ActorSystemImpl - Uncaught error from thread [play-akka.actor.default-dispatcher-5] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled
	java.lang.ExceptionInInitializerError: null
	        at controllers.Registration.startSignUp(Registration.java:95) ~[classes/:2.2.3]
	        at Routes$$anonfun$routes$1$$anonfun$applyOrElse$26$$anonfun$apply$26.apply(routes_routing.scala:377) ~[classes/:na]
	        at Routes$$anonfun$routes$1$$anonfun$applyOrElse$26$$anonfun$apply$26.apply(routes_routing.scala:377) ~[classes/:na]
	        at play.core.Router$HandlerInvoker$$anon$7$$anon$2.invocation(Router.scala:183) ~[play_2.10-2.2.3.jar:2.2.3]
	        at play.core.Router$Routes$$anon$1.invocation(Router.scala:377) ~[play_2.10-2.2.3.jar:2.2.3]
	        at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:56) ~[play_2.10-2.2.3.jar:2.2.3]
	Caused by: java.util.NoSuchElementException: None.get
	        at scala.None$.get(Option.scala:313) ~[scala-library.jar:na]
	        at scala.None$.get(Option.scala:311) ~[scala-library.jar:na]
	        at securesocial.core.providers.utils.Mailer$.<init>(Mailer.scala:33) ~[securesocial_2.10-2.1.4.jar:2.1.4]
	        at securesocial.core.providers.utils.Mailer$.<clinit>(Mailer.scala) ~[securesocial_2.10-2.1.4.jar:2.1.4]
	        at controllers.Registration.startSignUp(Registration.java:95) ~[classes/:2.2.3]
	        at Routes$$anonfun$routes$1$$anonfun$applyOrElse$26$$anonfun$apply$26.apply(routes_routing.scala:377) ~[classes/:na]

**Comment by nobiinu-and** [comment]
何となくですが、メールの送信のところでこけてそう。
メーラーの設定は、環境変数で行います。

SS_SMTP_HOST : ホスト名
SS_SMTP_PORT : ポート
SS_SMTP_SSL : SSLを使うかどうか(Boolean)
SS_SMTP_USER : SMTP認証に利用するユーザ
SS_SMTP_PASSWORD : SMTP認証に利用するパスワード
SS_SMTP_FROM :  メールのFROMに指定するメールアドレス
SS_SMTP_ENCRYPT_PASSWORD : SS_SMTP_PASSWORDを暗号化しておく場合はTRUEを
※ SS_SMTP_PASSWORD の暗号化についてはまた別途。

ダミーで良い場合は、 application.conf に以下の2行を追加して、サーバ再起動してみてください。
※ smtp.from は任意のメールアドレスでOKです。( boo@foo.baa でなくても可 )

> smtp.mock=true
> smtp.from="boo@foo.baa"

**Comment by hideakihal** [comment]
application.conf に以下の2行を追加することで上手く動きました。
ありがとうございます。

> smtp.mock=true
> smtp.from="boo@foo.baa"

ちなみに、以下のように起動時に同じ設定を行っていると思っていたのですが、何か違うのでしょうか？

> cd oot
> set SS_SMTP_FROM=test@foo.baa
> play "run -Dsmtp.mock=true"

**Comment by nobiinu-and** [comment]
play "run -Dsmtp.mock=true"

を

    play -Dsmtp.mock=true run

にするとどうでしょう? (runの中の引数にいれなくてよかったような…)

**Comment by hideakihal** [comment]
以下のようにすることで上手く動きました。

> play -Dsmtp.mock=true run

以下のようにしても大丈夫なようです。

> cd oot
> set SS_SMTP_FROM=test@foo.baa
> set _JAVA_OPTIONS=%_JAVA_OPTIONS% -Dsmtp.mock=true
> play run

Wikiのセットアップ手順にも反映しておきます。

**Comment by nobiinu-and** [comment]
ありがとうございます!!
application.conf を修正するのはあんまいい手ではない(pullするとき必ずコンフリクトするので)ので、
hideaki さんの方法のほうが良いと思います!!

Wikiのセットアップ手順への反映ありがとうございます。
